<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LIN9UEG" failures="2" tests="10" name="Surefire test" time="58.77" errors="0" timestamp="2024-06-05T08:00:41 IST">
  <testcase classname="com.tests.ChromeTest" name="testTitle" time="0.456"/>
  <testcase classname="com.tests.ChromeTest" name="clickOffers" time="2.473"/>
  <testcase classname="com.tests.ChromeTest" name="clickOrders" time="3.074"/>
  <testcase classname="com.tests.FirefoxTest" name="testTitle" time="0.043"/>
  <testcase classname="com.tests.FirefoxTest" name="clickOffers" time="3.693"/>
  <testcase classname="com.tests.FirefoxTest" name="clickOrders" time="2.92"/>
  <testcase classname="com.tests.SampleTest" name="capture_screenshot" time="0.344"/>
  <testcase classname="com.tests.SampleTest" name="capture_screenshot1" time="0.546">
    <failure type="java.lang.AssertionError" message="expected [200] but found [3000]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [3000]
at com.tests.SampleTest.capture_screenshot1(SampleTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- capture_screenshot1 -->
  <testcase classname="com.tests.SampleTest" name="capture_screenshot2" time="0.169"/>
  <testcase classname="com.tests.SampleTest" name="capture_screenshot3" time="0.163">
    <failure type="java.lang.AssertionError" message="expected [30] but found [3000]">
      <![CDATA[java.lang.AssertionError: expected [30] but found [3000]
at com.tests.SampleTest.capture_screenshot3(SampleTest.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- capture_screenshot3 -->
</testsuite> <!-- Surefire test -->
